export const DOCUMENT_TYPES = [
  "Giấy đi đường",
  "Giấy mời",
  "Giấy phép",
  "Phiếu chuyển",
  "Đề án",
  "Danh sách",
  "Báo cáo tuần",
  "Biên bản",
  "Công điện",
  "Hướng dẫn",
  "Kế hoạch",
  "Nghị định",
  "Công văn",
  "Báo cáo",
  "Kết luận",
  "Nghị quyết",
  "Quy định",
  "Quyết định",
  "Thông báo",
  "Thông tư",
  "Thông tư liên tịch",
  "Tờ trình",
  "Chương trình",
  "Hợp đồng",
  "Hợp đồng lao động",
  "Phiếu trình",
  "Giấy xác nhận",
  "Phương án",
  "Chỉ thị",
  "Phiếu đề xuất",
  "Lệnh điều xe",
  "Giấy giới thiệu",
  "Kết luận thanh tra",
  "Giấy ủy quyền",
  "Thư mời"
];

export const DOCUMENT_FIELDS: Record<string, string[]> = {
  default: ["title", "content", "receiver", "sender", "date", "signer"],
  "Giấy đi đường": ["title", "employeeName", "destination", "purpose", "startDate", "endDate", "vehicle"],
  "Giấy mời": ["title", "invitee", "time", "location", "purpose", "content"],
  "Quyết định": ["title", "basis", "content", "execution", "signer"],
  "Công văn": ["title", "receiver", "content", "sender", "signer"],
  "Hợp đồng lao động": ["employeeName", "position", "salary", "startDate", "endDate", "terms"],
  "Lệnh điều xe": ["driverName", "vehiclePlate", "destination", "purpose", "departureTime", "returnTime"],
};
